Dk 001 test global tool configuration page
Python2-QAForEveryone/jenkins-testing pull request #40
Opened 2021-06-24 04:39 UTC by dsk1975

2021-06-28 12:48 UTC, maximashuev reviewed
Looks. good.
Only one thing, naming convention. It would be more readable if it looks like this
locators_global_tool_config_page.py 
test_global_tool_config_page.py

2021-06-28 12:50 UTC, maximashuev commented
Please add a description with the links to Trello tasks like here 
https://github.com/Python2-QAForEveryone/jenkins-testing/pull/36

2021-06-29 04:12 UTC, dsk1975 commented
> Looks. good.
> Only one thing, naming convention. It would be more readable if it looks like this
> locators_global_tool_config_page.py
> test_global_tool_config_page.py

Thank you, I will rename it.

2021-06-29 04:13 UTC, dsk1975 commented
> Please add a description with the links to Trello tasks like here
> #36

For sure.

2021-07-01 21:17 UTC, Wis13 commented on tests/locators_global_tool_config_page.py
> +from selenium.webdriver.common.by import By
Этот файл нужно удалить, а локаторы перенести в GlobalTollConfiguration.py

2021-07-01 21:22 UTC, Wis13 commented on pages/GlobalToolConfiguration.py
> +from pages.BasePage import BasePage
Вроде договорились что все наследники от BasePage  заканчиваются в названии Page.

GlobalTollConfiguration.py -------> GlobalTollConfigurationPage.py

2021-07-03 02:45 UTC, maximashuev requested changes

2021-07-03 02:45 UTC, maximashuev commented on tests/locators_global_tool_config_page.py
> +from selenium.webdriver.common.by import By
Yes, please. Remove this file and move all locators to your page model.
example [link](https://github.com/Python2-QAForEveryone/jenkins-testing/pull/41)

2021-07-04 21:19 UTC, closed without merging

2021-07-04 21:21 UTC, dsk1975 commented
Closed this PR because I got a lot of conflicts. Going to build from scratch and open a new PR taking into the previous comments.