JN-15 create Multi-Configuration project
Python2-QAForEveryone/jenkins-testing pull request #52
Opened 2021-07-27 15:19 UTC by Jenny-ai

created NewItemPage, ProjectPage
StringUtils is for random string generators
4 tests added: create multi-configuration project with String, Int, String+Int, Special Symbol names

[task](https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-15)

2021-07-27 20:17 UTC, Wis13 requested changes

2021-07-27 20:17 UTC, Wis13 commented on pages/NewItemPage.py
> +    SAVE_BUTTON = (By.XPATH, '//button[@type="button"][text()="Save"]')
Здесь замени XPATH и все тесты проходят SAVE_BUTTON = (By.ID, "yui-gen30-button")

2021-07-27 20:34 UTC, Wis13 requested changes

2021-07-27 20:34 UTC, Wis13 commented on pages/NewItemPage.py
> +
URL_CREATE_ITEM = "http://localhost:8080/job/New%20Proj/configure"
    URL_PROJECT = "http://localhost:8080/job/New%20Proje/configure"
Два непонятных локатора. Вопервых в  ТестData.py есть такая строка BASE_URL = 'http://localhost:8080/', это значит что все должны использовать синтаксис URL_XXX = Base_URL + "job/New%20Proj/configure". Дальше у каждой job  есть имя которое вы генерите и поэтому у каждой Job будет своя страница configure и URL будет выглядеть так: URL_PROJECT = Base_URL + f"job/{name}/configure" где {name} - это переменная которая генериться вашим random. 
URL_CREATE_ITEM = Base_URL + "view/all/newJob"

2021-07-28 01:04 UTC, Jenny-ai commented on tests/test_multi_configuration_project.py
> +        special_symbol = generate_random_special_symbol(1)
вижу ты глубоко исследовал эту тему! Я не буду делать очень подробное тестирование имени, потому что хочу быстрее сделать end to end.

2021-07-28 01:05 UTC, Jenny-ai commented on pages/NewItemPage.py
> +    SAVE_BUTTON = (By.XPATH, '//button[@type="button"][text()="Save"]')
"yui-gen30-button" - это динамический id! Следующий билд - и все перестанет работать. Я имела печальный опыт с динамическими ай-ди. Больше их не использую.

2021-07-28 01:06 UTC, Jenny-ai commented on pages/NewItemPage.py
> +
удалю, спасибо!

2021-07-28 01:07 UTC, Jenny-ai commented on tests/test_multi_configuration_project.py
> +            NewItemPageLocators.ERROR_MESSAGE) == "» ‘" + special_symbol + "’ is an unsafe character"
а ты знаешь когда одни кавычки а когда двое?

2021-07-28 06:52 UTC, Wis13 commented on tests/test_multi_configuration_project.py
> +            NewItemPageLocators.ERROR_MESSAGE) == "» ‘" + special_symbol + "’ is an unsafe character"
Нет не знаю :)

2021-07-28 06:54 UTC, Wis13 commented on tests/test_multi_configuration_project.py
> +        special_symbol = generate_random_special_symbol(1)
Глубоко не глубоко твои методы будут всегда падать потому как у них результат разный. И единственный выход если ничего не пенять просто удалить эти тесты :)

2021-07-28 06:58 UTC, Wis13 commented on pages/NewItemPage.py
> +    SAVE_BUTTON = (By.XPATH, '//button[@type="button"][text()="Save"]')
А как ты это определила что он динамический? Научи меня, я серьезно!

2021-07-29 13:43 UTC, Jenny-ai commented on pages/NewItemPage.py
> +    SAVE_BUTTON = (By.XPATH, '//button[@type="button"][text()="Save"]')
когда видишь неосмысленный id с цифрами - он динамический. Они генерируются при каком-то событии.

2021-07-29 13:53 UTC, Jenny-ai commented on tests/test_multi_configuration_project.py
> +        special_symbol = generate_random_special_symbol(1)
Я поняла, то есть . , + и ! будут давать разные меседжи. Сейчас перепигем, чтобы не обращал внимания на текст меседжа.

2021-07-29 13:53 UTC, Jenny-ai commented on tests/test_multi_configuration_project.py
> +            NewItemPageLocators.ERROR_MESSAGE) == "» ‘" + special_symbol + "’ is an unsafe character"
я удалю проверку на текст ошибки

2021-07-31 15:03 UTC, maximashuev commented on tests/test_multi_configuration_project.py
> +                             FolderPage.name_empty]
I think those should belong to the Page module. Like we do with locators.

2021-07-31 15:03 UTC, maximashuev commented on pages/StringUtils.py
> +    return ''.join(random.choices(string.punctuation, k=number_of_symbols))
The name of the module should contain "Page".

2021-08-01 01:56 UTC, Jenny-ai commented on tests/test_multi_configuration_project.py
> +                             FolderPage.name_empty]
я могу вынести конечно, но похоже Page y троих из нас должна быть одна и мы там ногу сломим, если еще туда будем ложить тестовые данные

2021-08-01 01:56 UTC, Jenny-ai commented on pages/StringUtils.py
> +    return ''.join(random.choices(string.punctuation, k=number_of_symbols))
не должно быть Page, это вспомогательный класс, он генерит рандомные значения

2021-08-02 23:30 UTC, Wis13 approved these changes

2021-08-02 23:31 UTC, merged