Nk pipeline
Python2-QAForEveryone/jenkins-testing pull request #62
Opened 2021-08-18 04:19 UTC by NadezdaKataeva

1. Creating  a pipeline with name consisting with 1)letters or 2)digits or 3)letters and digits,   or 4)pipeline_ plus random 3 digits. Positive testing. 2. Verifying a user can "Build now". 3. Verifying that name of the created pipeline (4) is present in the tab

2021-08-20 03:40 UTC, Jenny-ai requested changes

2021-08-21 01:47 UTC, NadezdaKataeva commented on conftest.py
>          driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
Thank you, done.

2021-08-21 01:48 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +from pages.BasePage import BasePage
Thank you. Done!

2021-08-21 01:52 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +
В какой Page, уже есть общая или мне свою надо создать?

2021-08-21 01:53 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +        driver.click(NewItemPageLocators.OK_BUTTON)
Наверное можно удалить. Удалю.

2021-08-21 01:56 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +        driver.get_element(NewPipelineConfigure.SAVE_PIPELINE)
OK. Хотя когда многошаговый тест,  проверки не помешали бы (я так думаю)

2021-08-21 02:01 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +        assert driver.is_element_present(self.TAB_LOCATOR_VALID)
Таск есть, в юзер стори тоже, но он не в этом спринте(After creating Pipeline will be shown in main dashboard page in tab “ All”). Скип сделаю на тест? В следующий спринт расскомментирую.

2021-08-22 13:07 UTC, Jenny-ai commented on tests/test_create_pipeline_positive.py
> +        assert driver.is_element_present(self.TAB_LOCATOR_VALID)
тогда можешь оставить и если это весь таск, то можешь его перетащить в этот спринт и закрыть

2021-08-22 13:11 UTC, Jenny-ai commented on tests/test_create_pipeline_positive.py
> +
ну смотря какие - SAVE_PIPELINE = (By.XPATH, '//*[@type="submit"]') - это то же самое что и SAVE_BUTTON = (By.XPATH, '//span[@name="Submit"]') в NewItemPage
там есть все кнопки на создание проекта, если там нету чего - добавляй
после создания твоего проекта, ты его видишь на ProjectPage - там тоже есть какой-то функционал - бери используй, дописывай свое
Если ты ходишь еще на какие то страницы - нужно создавать отдельный файл

2021-08-24 00:17 UTC, NadezdaKataeva commented on tests/test_create_pipeline_positive.py
> +
Создала новую страницу PipelinePage с локаторами.

2021-08-31 03:41 UTC, Jenny-ai approved these changes
lgtm

2021-08-31 03:47 UTC, merged